# Generated by Django 5.0.6 on 2024-05-26 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="detallefactura",
            options={"verbose_name_plural": "Detalles de Factura"},
        ),
        migrations.AlterModelOptions(
            name="devolucion",
            options={"verbose_name_plural": "Devoluciones"},
        ),
        migrations.AlterModelOptions(
            name="factura",
            options={"verbose_name_plural": "Facturas"},
        ),
        migrations.AlterModelOptions(
            name="inventario",
            options={"verbose_name_plural": "Inventarios"},
        ),
        migrations.AlterModelOptions(
            name="producto",
            options={"verbose_name_plural": "Productos"},
        ),
        migrations.RemoveField(
            model_name="producto",
            name="stock",
        ),
    ]
